name: Elixir CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04          # ← Cambia qui

    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: '1.18'
